### ISSUE TITLE
Assembly error

### ISSUE THREAD

**Issue by Maxumka** [frognix/cl-snake#1]
Hello, frognix, i really want to play cl-snake, but project not assembly at me(
I have this log message, when assembly project.

This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "sketch":
  Load 1 ASDF system:
    sketch
; Loading "sketch"
..........While evaluating the form starting at line 6, column 0
  of #P"/home/max/cl-snake/./build.lisp":
Unhandled CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                       {1004DE0233}>:
  Unable to load any of the alternatives:
   ("libSDL2_image-2.0.so.0" "libSDL2_image")

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1004DE0233}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1002EE6503}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1002EE6503}>)
2: (INVOKE-DEBUGGER #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1002EE6503}>)
3: (ERROR CFFI:LOAD-FOREIGN-LIBRARY-ERROR :FORMAT-CONTROL "Unable to load any of the alternatives:~%   ~S" :FORMAT-ARGUMENTS (("libSDL2_image-2.0.so.0" "libSDL2_image")))
4: (CFFI::FL-ERROR "Unable to load any of the alternatives:~%   ~S" ("libSDL2_image-2.0.so.0" "libSDL2_image"))
5: (CFFI::TRY-FOREIGN-LIBRARY-ALTERNATIVES LIBSDL2-IMAGE ("libSDL2_image-2.0.so.0" "libSDL2_image") NIL)
6: ((FLET CFFI::%DO-LOAD :IN CFFI::%DO-LOAD-FOREIGN-LIBRARY) #<CFFI:FOREIGN-LIBRARY LIBSDL2-IMAGE> LIBSDL2-IMAGE (:OR "libSDL2_image-2.0.so.0" "libSDL2_image"))
7: (CFFI:LOAD-FOREIGN-LIBRARY LIBSDL2-IMAGE :SEARCH-PATH NIL)
8: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /home/max/.cache/common-lisp/sbcl-2.1.1-linux-x64/usr/lib/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/library.fasl" {1002EE0573}> :TABLE #(27 SET *PACKAGE* "SDL2-IMAGE" #<PACKAGE "CFFI"> CFFI::REGISTER-FOREIGN-LIBRARY #<PACKAGE "SDL2-IMAGE"> LIBSDL2-IMAGE :DARWIN :OR :FRAMEWORK "SDL2_image" ...) :STACK #(0 CFFI:LOAD-FOREIGN-LIBRARY LIBSDL2-IMAGE ((:DARWIN (:OR # #1=#)) #2=(:UNIX (:OR "libSDL2_image-2.0.so.0" "libSDL2_image")) #3=(:WINDOWS "SDL2_image.dll") #4=(T #1#)) #2# #3# #4# #1# 0 0 0 0 ...) :NAME-BUFFER #("" "LOAD-FOREIGN-LIBRARYRARY") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL) NIL)
9: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /home/max/.cache/common-lisp/sbcl-2.1.1-linux-x64/usr/lib/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/library.fasl" {1002EE0573}> NIL NIL)
10: ((FLET SB-FASL::THUNK :IN LOAD))
11: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (FLET SB-FASL::THUNK :IN LOAD) {7F4E086E5A6B}> #<SB-SYS:FD-STREAM for "file /home/max/.cache/common-lisp/sbcl-2.1.1-linux-x64/usr/lib/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/library.fasl" {1002EE0573}>)
12: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /home/max/.cache/common-lisp/sbcl-2.1.1-linux-x64/usr/lib/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/library.fasl" {1002EE0573}> T)
13: (LOAD #P"/home/max/.cache/common-lisp/sbcl-2.1.1-linux-x64/usr/lib/quicklisp/dists/quicklisp/software/cl-sdl2-image-20190202-git/src/library.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
14: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<FUNCTION (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {1002EDFD0B}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
15: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2-image" "library">)
16: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
17: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2-image" "library">) [fast-method]
18: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "sdl2-image" "library">) [fast-method]
19: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100367C1C3}>) [fast-method]
20: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
21: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100367C1C3}>) [fast-method]
22: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "sketch"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
23: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "sketch"> :VERBOSE NIL)
24: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
25: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "sketch"> :VERBOSE NIL) [fast-method]
26: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "sketch" :VERBOSE NIL)
27: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
28: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "sketch" :VERBOSE NIL) [fast-method]
29: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100367425B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
30: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
31: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100366D8BB}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
32: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "sketch" :VERBOSE NIL) [fast-method]
33: (ASDF/OPERATE:LOAD-SYSTEM "sketch" :VERBOSE NIL)
34: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {100366C06B}>)
35: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "sketch" :PROMPT NIL)
36: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {10032DE8CB}>) [fast-method]
37: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1002BDE773}> #<FUNCTION (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {10032DE8CB}>) [fast-method]
38: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :SKETCH :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
39: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<FUNCTION (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {10032CEF4B}>)
40: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :SKETCH) #<NULL-LEXENV>)
41: (SB-EXT:EVAL-TLF (QUICKLISP-CLIENT:QUICKLOAD :SKETCH) 3 NIL)
42: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (QUICKLISP-CLIENT:QUICKLOAD :SKETCH) 3)
43: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (QUICKLISP-CLIENT:QUICKLOAD :SKETCH) :CURRENT-INDEX 3)
44: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {10009EB29B}> #<SB-C::SOURCE-INFO {10009EB263}> SB-C::INPUT-ERROR-IN-LOAD)
45: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /home/max/cl-snake/./build.lisp" {10009E9F33}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
46: ((FLET SB-FASL::THUNK :IN LOAD))
47: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (FLET SB-FASL::THUNK :IN LOAD) {7F4E086E789B}> #<SB-INT:FORM-TRACKING-STREAM for "file /home/max/cl-snake/./build.lisp" {10009E9F33}>)
48: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /home/max/cl-snake/./build.lisp" {10009E9F33}> NIL)
49: (LOAD #P"./build.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
50: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:LOAD . "./build.lisp") (:QUIT)))
51: (SB-IMPL::TOPLEVEL-INIT)
52: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
53: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
54: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
;   caught 1 fatal ERROR condition

**Comment by frognix** [comment]
I forgot to add sketch dependencies to the list of project requirements. Now it's fixed (18a16f274dd71ac681c21615cbde1fbed8e54e84).
Please install the required packages and try to build the project again.

**Comment by Maxumka** [comment]
I install new packages, but after assembly not exec snake
This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "sketch":
  Load 1 ASDF system:
    sketch
; Loading "sketch"
............
[undoing binding stack and other enclosing state... done]
[performing final GC... done]
[defragmenting immobile space... (fin,inst,fdefn,code,sym)=1572+1266+27567+28238+34336... done]
[saving current Lisp image into snake:
writing 0 bytes from the read-only space at 0x50000000
writing 736 bytes from the static space at 0x50100000
writing 46301184 bytes from the dynamic space at 0x1000000000
writing 2777088 bytes from the immobile space at 0x50200000
writing 16994304 bytes from the immobile space at 0x52000000
done]

**Comment by frognix** [comment]
Check the project directory, there should be an executable file named snake

**Comment by Maxumka** [comment]
i execute this file and get this 
Unhandled SDL2::SDL-RC-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                          {1000C300D3}>:
  SDL Error (-1): Unable to make GL context current

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000C300D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SDL2::SDL-RC-ERROR {1004B2DF23}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SDL2::SDL-RC-ERROR {1004B2DF23}>)
2: (INVOKE-DEBUGGER #<SDL2::SDL-RC-ERROR {1004B2DF23}>)
3: (ERROR SDL2::SDL-RC-ERROR :RC -1 :STRING "Unable to make GL context current")
4: (SDL2:GL-MAKE-CURRENT #<SDL2-FFI:SDL-WINDOW {#X7F451C2E2E20}> #<SDL2-FFI::SDL-GLCONTEXT {#X7F451C31D118}>)
5: ((SB-PCL::EMF KIT.SDL2:WINDOW-EVENT) #<unused argument> #<unused argument> #<SNAKE::SNAKE-WINDOW {1002E33693}> :SHOWN 2115 0 0)
6: (KIT.SDL2::MAIN-LOOP-FUNCTION #<SDL2-FFI:SDL-EVENT {#X55567850B190}> NIL)
7: (KIT.SDL2::MAIN-LOOP)
8: ((LAMBDA NIL :IN KIT.SDL2:START))
9: (SDL2::HANDLE-MESSAGE (#<FUNCTION (LAMBDA NIL :IN KIT.SDL2:START) {1002E33F4B}>))
10: (SDL2::SDL-MAIN-THREAD)
11: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
13: (SB-IMPL::START-LISP)

**Comment by frognix** [comment]
This is most likely a bug in SDL related to EGLStream.
